"""empty message

Revision ID: 9589744fd8c3
Revises: 7d9f298a5204
Create Date: 2024-11-05 10:15:24.911377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9589744fd8c3'
down_revision = '7d9f298a5204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explorer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'explorer', ['explorer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('explorer_id')

    # ### end Alembic commands ###
